version: 2

sources:
  - name: staging
    database: dezoomcamp2024-412513
    schema: trips_data_all

      # loaded_at_field: record_loaded_at
    tables:
      - name: fhv_trips
      - name: green_tripdata
      - name: yellow_tripdata 

